name: political_spending_infographic
version: '1.0'
profile: meltano
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: logs
packages-install-path: dbt_packages

clean-targets:
  - dbt_packages
  - logs
  - docs

seeds:
  political_spending_infographic:
    +schema: source

models:
  political_spending_infographic:
    staging:
      +materialized: view
    marts:
      +materialized: table
    analysis:
      +materialized: table
