# DuckDB config reference:
config:
  send_anonymous_usage_stats: false
  use_colors: true

meltano:
  target: main
  outputs:
    main:
      type: duckdb
      threads: 4
      path: "{{ env_var('DBT_DUCKDB_PATH') }}"
